/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  safelist: [
    // Accent colors
    'border-accent-light',
    'border-accent-dark',
    'border-accent',
    'bg-accent-light',
    'bg-accent-dark',
    'bg-accent',
    'text-accent-light',
    'text-accent-dark',
    'text-accent',
    // Primary colors
    'border-primary-500',
    'border-primary-600',
    'bg-primary-500',
    'bg-primary-600',
    'text-primary-500',
    'text-primary-600',
    // Secondary colors
    'border-secondary-200',
    'border-secondary-300',
    'bg-secondary-200',
    'bg-secondary-300',
    'text-secondary-800',
    'text-secondary-900',
  ],
  theme: {
    fontFamily: {
      sans: [
        '"Inter"',
        '"BIZ UDGothic"',
        "system-ui",
        "-apple-system",
        "BlinkMacSystemFont",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "sans-serif",
      ],
    },
    screens: {
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
      "2xl": "1536px",
    },
    colors: {
      // Tailwindのデフォルト色を保持
      inherit: "inherit",
      current: "current",
      transparent: "transparent",
      black: "#000",
      white: "#fff",
      gray: {
        50: "#f9fafb",
        100: "#f3f4f6",
        200: "#e5e7eb",
        300: "#d1d5db",
        400: "#9ca3af",
        500: "#6b7280",
        600: "#4b5563",
        700: "#374151",
        800: "#1f2937",
        900: "#111827",
        950: "#030712",
      },
      // カスタムカラー
      background: "hsl(var(--background))",
      foreground: "hsl(var(--foreground))",
      destructive: "hsl(var(--destructive))",
      ring: "hsl(var(--ring))",
      // Primary (11段階)
      primary: {
        50: "var(--color-primary-50)",
        100: "var(--color-primary-100)",
        200: "var(--color-primary-200)",
        300: "var(--color-primary-300)",
        400: "var(--color-primary-400)",
        500: "var(--color-primary-500)",
        600: "var(--color-primary-600)",
        700: "var(--color-primary-700)",
        800: "var(--color-primary-800)",
        900: "var(--color-primary-900)",
        950: "var(--color-primary-950)",
        DEFAULT: "var(--color-primary-500)",
      },
      // Secondary (11段階)
      secondary: {
        50: "var(--color-secondary-50)",
        100: "var(--color-secondary-100)",
        200: "var(--color-secondary-200)",
        300: "var(--color-secondary-300)",
        400: "var(--color-secondary-400)",
        500: "var(--color-secondary-500)",
        600: "var(--color-secondary-600)",
        700: "var(--color-secondary-700)",
        800: "var(--color-secondary-800)",
        900: "var(--color-secondary-900)",
        950: "var(--color-secondary-950)",
        DEFAULT: "var(--color-secondary-500)",
      },
      // Accent (4段階)
      accent: {
        DEFAULT: "var(--color-accent)",
        light: "var(--color-accent-light)",
        "super-light": "var(--color-accent-super-light)",
        dark: "var(--color-accent-dark)",
      },
      // 後方互換性のため
      "bg-sub": "var(--color-secondary-50)",
    },
  },
  plugins: [],
};
